### ISSUE TITLE
File already exists at path

### ISSUE THREAD

**Issue by nasyrov** [protonemedia/laravel-ffmpeg#220]
Hi @pascalbaljet ,

Thanks for the awesome package!

I'm getting the error once I pull the file from S3 and trying to save to enhanced copy of it back to S3.

```php
        FFMpeg::fromDisk('s3')
            ->open('path/to/my-file.mpga')
            ->addFilter(new CustomFilter('loudnorm=I=-14:TP=-3:LRA=11'))
            ->export()
            ->inFormat(
                (new Mp3)
                    ->setAudioChannels(1)
                    ->setAudioKiloBitrate(220)
            )
            ->withVisibility('public')
            ->save('path/to/my-enhanced-file.mp3')
            ->cleanupTemporaryFiles();
```

It pulls the original file to `tmp` folder and once it's done with all the manipulations it tries to upload back the original and enhanced file back to s3 and that's where the error happens.

```log
[2020-07-14 18:34:19] staging.ERROR: File already exists at path: public/NDg=/M3unTZQV3CVJkC9HArzIzppQiSjDJg-metadGVzdDIyMi5tcDM=-.mpga {"exception":"[object] (Illuminate\\Contracts\\Filesystem\\FileExistsException(code: 0): File already exists at path: public/NDg=/M3unTZQV3CVJkC9HArzIzppQiSjDJg-metadGVzdDIyMi5tcDM=-.mpga at /app/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:464)
```

**Comment by pascalbaljet** [comment]
Could you share the full log and stack trace, and also provide the real filenames?

**Comment by nasyrov** [comment]
Hi @pascalbaljet ,

Here's the full exception log:

```log
2020-07-15T08:08:03.797940+00:00 app[worker.1]: [2020-07-15 08:08:03][cd7hX666phuiCwmItCEtZX47ZonibCUR] Processing: App\Jobs\EnhanceUpload
2020-07-15T08:08:03.838744+00:00 app[worker.1]: [2020-07-15 08:08:03] staging.INFO: ffprobe running command '/app/vendor/ffmpeg/ffprobe' '/tmp/847086962-0808732001594800483/public/NDg=/vGUoU1xZjK1dHrb5UMEnku19BgotDF-metadGVzdDIyMi5tcDM=-.mpga' '-show_streams' '-print_format' 'json'  
2020-07-15T08:08:03.838745+00:00 app[worker.1]: 
2020-07-15T08:08:03.848593+00:00 app[worker.1]: [2020-07-15 08:08:03] staging.INFO: ffprobe executed command successfully  
2020-07-15T08:08:03.848594+00:00 app[worker.1]: 
2020-07-15T08:08:03.878446+00:00 app[worker.1]: [2020-07-15 08:08:03] staging.INFO: ffmpeg running command '/app/vendor/ffmpeg/ffmpeg' '-y' '-i' '/tmp/847086962-0808732001594800483/public/NDg=/vGUoU1xZjK1dHrb5UMEnku19BgotDF-metadGVzdDIyMi5tcDM=-.mpga' '-af' 'loudnorm=I=-14:TP=-3:LRA=11' '-threads' '12' '-acodec' 'libmp3lame' '-b:a' '220k' '-ac' '1' '/tmp/847086962-0808732001594800483/public/NDg=/enhanced/vGUoU1xZjK1dHrb5UMEnku19BgotDF-metadGVzdDIyMi5tcDM=-.mp3'  
2020-07-15T08:08:03.878447+00:00 app[worker.1]: 
2020-07-15T08:08:05.352994+00:00 app[worker.1]: [2020-07-15 08:08:05] staging.INFO: ffmpeg executed command successfully  
2020-07-15T08:08:05.352997+00:00 app[worker.1]: 
2020-07-15T08:08:05.361616+00:00 app[worker.1]: [2020-07-15 08:08:05] staging.ERROR: File already exists at path: public/NDg=/enhanced/vGUoU1xZjK1dHrb5UMEnku19BgotDF-metadGVzdDIyMi5tcDM=-.mp3 {"exception":"[object] (Illuminate\\Contracts\\Filesystem\\FileExistsException(code: 0): File already exists at path: public/NDg=/enhanced/vGUoU1xZjK1dHrb5UMEnku19BgotDF-metadGVzdDIyMi5tcDM=-.mp3 at /app/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:464)
2020-07-15T08:08:05.361617+00:00 app[worker.1]: [stacktrace]
2020-07-15T08:08:05.361618+00:00 app[worker.1]: #0 /app/vendor/pbmedia/laravel-ffmpeg/src/Filesystem/Media.php(127): Illuminate\\Filesystem\\FilesystemAdapter->writeStream()
2020-07-15T08:08:05.361618+00:00 app[worker.1]: #1 /app/vendor/pbmedia/laravel-ffmpeg/src/Exporters/MediaExporter.php(131): ProtoneMedia\\LaravelFFMpeg\\Filesystem\\Media->copyAllFromTemporaryDirectory()
2020-07-15T08:08:05.361619+00:00 app[worker.1]: #2 /app/app/Jobs/EnhanceUpload.php(56): ProtoneMedia\\LaravelFFMpeg\\Exporters\\MediaExporter->save()
2020-07-15T08:08:05.361619+00:00 app[worker.1]: #3 [internal function]: App\\Jobs\\EnhanceUpload->handle()
2020-07-15T08:08:05.361619+00:00 app[worker.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
2020-07-15T08:08:05.361620+00:00 app[worker.1]: #5 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2020-07-15T08:08:05.361620+00:00 app[worker.1]: #6 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
2020-07-15T08:08:05.361621+00:00 app[worker.1]: #7 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2020-07-15T08:08:05.361621+00:00 app[worker.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
2020-07-15T08:08:05.361622+00:00 app[worker.1]: #9 /app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
2020-07-15T08:08:05.361622+00:00 app[worker.1]: #10 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
2020-07-15T08:08:05.361625+00:00 app[worker.1]: #11 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-15T08:08:05.361625+00:00 app[worker.1]: #12 /app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
2020-07-15T08:08:05.361626+00:00 app[worker.1]: #13 /app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
2020-07-15T08:08:05.361626+00:00 app[worker.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
2020-07-15T08:08:05.361626+00:00 app[worker.1]: #15 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-15T08:08:05.361627+00:00 app[worker.1]: #16 /app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
2020-07-15T08:08:05.361627+00:00 app[worker.1]: #17 /app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
2020-07-15T08:08:05.361628+00:00 app[worker.1]: #18 /app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
2020-07-15T08:08:05.361628+00:00 app[worker.1]: #19 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
2020-07-15T08:08:05.361628+00:00 app[worker.1]: #20 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process()
2020-07-15T08:08:05.361629+00:00 app[worker.1]: #21 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob()
2020-07-15T08:08:05.361629+00:00 app[worker.1]: #22 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
2020-07-15T08:08:05.361630+00:00 app[worker.1]: #23 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
2020-07-15T08:08:05.361630+00:00 app[worker.1]: #24 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
2020-07-15T08:08:05.361631+00:00 app[worker.1]: #25 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
2020-07-15T08:08:05.361631+00:00 app[worker.1]: #26 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2020-07-15T08:08:05.361631+00:00 app[worker.1]: #27 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
2020-07-15T08:08:05.361632+00:00 app[worker.1]: #28 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2020-07-15T08:08:05.361637+00:00 app[worker.1]: #29 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
2020-07-15T08:08:05.361637+00:00 app[worker.1]: #30 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
2020-07-15T08:08:05.361638+00:00 app[worker.1]: #31 /app/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
2020-07-15T08:08:05.361638+00:00 app[worker.1]: #32 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
2020-07-15T08:08:05.361639+00:00 app[worker.1]: #33 /app/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
2020-07-15T08:08:05.361639+00:00 app[worker.1]: #34 /app/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
2020-07-15T08:08:05.361639+00:00 app[worker.1]: #35 /app/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
2020-07-15T08:08:05.361639+00:00 app[worker.1]: #36 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
2020-07-15T08:08:05.361640+00:00 app[worker.1]: #37 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
2020-07-15T08:08:05.361640+00:00 app[worker.1]: #38 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
```

**Comment by nasyrov** [comment]
Problem happens on `copyAllFromTemporaryDirectory` method

```php
$outputMedia->copyAllFromTemporaryDirectory($this->visibility);
```

As explain earlier it downloads a file from S3 to the temp folder and once `copyAllFromTemporaryDirectory` is called it tries to upload the existing file back.

**Comment by nasyrov** [comment]
Hi @pascalbaljet ,

Do you have any thoughts about it? Perhaps I can make a PR?

**Comment by susanu** [comment]
Is there any workaround for this?

**Comment by Rusya13** [comment]
I don't if this is ok, but I just added `'disable_asserts' => true` into 's3' array in `config/filesystems.php`. Works for me.

**Comment by pascalbaljet** [comment]
I'll close this issue as it seems related to the S3 config and not to this package.
