### ISSUE TITLE
Unable to encrypt hls segments / Unable to probe encrypted hls segments

### ISSUE THREAD

**Issue by wayne-thorley** [protonemedia/laravel-ffmpeg#259]
I've ran into several issues whilst trying to encrypt hls segments.

Firstly, it seems the package overwrites any custom `setAdditionalParameters` on the format.

```php
$lowBitrateFormat  = (new X264())->setAdditionalParameters(['-hls_key_info_file', $this->keyPaths['keyinfo']]);
```

My additional parameters are completely ignored, unless I change the `addHLSParametersToFormat` function in ProtoneMedia\LaravelFFMpeg\Exporters\HLSExporter to merge any existing additional parameters:

```php
$format->setAdditionalParameters(array_merge([
    '-sc_threshold',
    '0',
    '-g',
    $this->keyFrameInterval,
    '-hls_playlist_type',
    'vod',
    '-hls_time',
    $this->segmentLength,
    '-hls_segment_filename',
    $disk->makeMedia($segmentsPattern)->getLocalPath(),
], $format->getAdditionalParameters()));
```

Having done that the encryption worked, however it resulted in another error when subsequently trying to probe the segment file during the save process:

`ffprobe running command '/usr/local/ffmpeg/bin/ffprobe' '../../1607701889_5fd3958162766/1607701889_5fd3958162766_0_1000_00000.ts' '-show_streams' '-print_format' 'json'`

`../../1607701889_5fd3958162766/1607701889_5fd3958162766_0_1000_00000.ts: Invalid data found when processing input`

I'm guessing it's failing because the segment isn't being decrypted - so we need to somehow pass in the .keyinfo file?

Any ideas?

Log output below:
```
[2020-12-11 15:52:00] local.ERROR: Unable to probe /storage/app/public/videos/stream/1607701889_5fd3958162766/1607701889_5fd3958162766_0_1000_00000.ts {"exception":"[object] (FFMpeg\\Exception\\RuntimeException(code: 0): Unable to probe /storage/app/public/videos/stream/1607701889_5fd3958162766/1607701889_5fd3958162766_0_1000_00000.ts at /vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php:263)
[stacktrace]
#0 /vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(206): FFMpeg\\FFProbe->probe('/Users/waynetho...', '-show_streams', 'streams')
#1 /vendor/pbmedia/laravel-ffmpeg/src/FFMpeg/FFProbe.php(51): FFMpeg\\FFProbe->streams('/Users/waynetho...')
#2 /vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(95): ProtoneMedia\\LaravelFFMpeg\\FFMpeg\\FFProbe->streams('/Users/waynetho...')
#3 /vendor/pbmedia/laravel-ffmpeg/src/Drivers/PHPFFMpeg.php(113): FFMpeg\\FFMpeg->open('/Users/waynetho...')
#4 /vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(119): ProtoneMedia\\LaravelFFMpeg\\Drivers\\PHPFFMpeg->open(Object(ProtoneMedia\\LaravelFFMpeg\\Filesystem\\MediaCollection))
#5 /vendor/pbmedia/laravel-ffmpeg/src/MediaOpener.php(203): ProtoneMedia\\LaravelFFMpeg\\MediaOpener->getDriver()
#6 /vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php(30): ProtoneMedia\\LaravelFFMpeg\\MediaOpener->__call('getFormat', Array)
#7 /vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php(65): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator->getBandwidth(Object(ProtoneMedia\\LaravelFFMpeg\\MediaOpener))
#8 [internal function]: ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator->ProtoneMedia\\LaravelFFMpeg\\Exporters\\{closure}(Object(ProtoneMedia\\LaravelFFMpeg\\Filesystem\\Media), 0)
#9 /vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#10 /vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php(74): Illuminate\\Support\\Collection->map(Object(Closure))
#11 /vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSExporter.php(178): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator->get(Array, Object(ProtoneMedia\\LaravelFFMpeg\\Drivers\\PHPFFMpeg))
#12 /vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(635): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSExporter->ProtoneMedia\\LaravelFFMpeg\\Exporters\\{closure}(Object(Illuminate\\Support\\Collection))
#13 /vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSExporter.php(184): Illuminate\\Support\\Collection->pipe(Object(Closure))
```

**Comment by pascalbaljet** [comment]
Thanks for reporting, I'll look into this. I've been working on an encryption feature for a while but need some time to finish it :)

**Comment by pascalbaljet** [comment]
WIP: https://github.com/protonemedia/laravel-ffmpeg/pull/262

**Comment by wayne-thorley** [comment]
This looks amazing! I was struggling to think of how to mangle a workaround in, but what you've done is beautifully elegant and much more robust. Amazing stuff, can't wait to try it out! Legend 🙌

**Comment by pascalbaljet** [comment]
Thanks! I've just tagged v7.5 which includes all the encryption features (see docs).
