### ISSUE TITLE
ffmpeg failed to execute command

### ISSUE THREAD

**Issue by skfaisal93** [protonemedia/laravel-ffmpeg#387]
How can I export a single frame out of video. I have used code from documentaion and that works on localhost but not working on server

My code
```
FFMpeg::fromDisk($this->video->disk)
            ->open($this->video->path . $this->video->file_name)
            ->getFrameFromSeconds(10)
            ->export()
            ->addFilter(function (FrameFilters $filters) {
                $filters->custom('scale=1280:720');
            })
            ->toDisk('s3.public')
            ->save($this->frame_path);
```

Error

```
Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-ss' '00:00:10.00' '-i' '/var/www/html/my-project/storage/app/media-library/abed1e5658b3ad23c38c22646968e4f2/files/media/videos/2022/03/154dfb8c-2f01-4098-9887-0404dac260a1/fc46fe1d97502ffb637a9954a90a225e.mp4' '-vframes' '1' '-f' 'image2' '-vf' 'scale=1280:720' '/tmp/9c6157a2ca389acd/abed1e5658b3ad23c38c22646968e4f2/files/video-posters/154dfb8c-2f01-4098-9887-0404dac260a1.webp':

Error Output:

 ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/html/my-project/storage/app/media-library/abed1e5658b3ad23c38c22646968e4f2/files/media/videos/2022/03/154dfb8c-2f01-4098-9887-0404dac260a1/fc46fe1d97502ffb637a9954a90a225e.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2015-08-07T09:13:02.000000Z
  Duration: 00:00:30.53, start: 0.000000, bitrate: 411 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 480x270 [SAR 1:1 DAR 16:9], 301 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Video Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 112 kb/s (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Audio Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> webp (libwebp_anim))
Press [q] to stop, [?] for help
Output #0, image2, to '/tmp/9c6157a2ca389acd/abed1e5658b3ad23c38c22646968e4f2/files/video-posters/154dfb8c-2f01-4098-9887-0404dac260a1.webp':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: webp (libwebp_anim), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2015-08-07T09:13:02.000000Z
      handler_name    : L-SMASH Video Handler
      encoder         : Lavc58.54.100 libwebp_anim
[image2 @ 0x55911dd965c0] Could not get frame filename number 2 from pattern '/tmp/9c6157a2ca389acd/abed1e5658b3ad23c38c22646968e4f2/files/video-posters/154dfb8c-2f01-4098-9887-0404dac260a1.webp'. Use '-frames:v 1' for a single image, or '-update' option, or use a pattern such as %03d within the filename.
av_interleaved_write_frame(): Invalid argument
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.06 bitrate=N/A speed=0.778x    
video:9kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
 in /var/www/html/my-project/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/ProcessRunner.php:94
Stack trace:
#0 /var/www/html/my-project/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure()
#1 /var/www/html/my-project/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\BinaryDriver\ProcessRunner->run()
#2 /var/www/html/my-project/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\BinaryDriver\AbstractBinary->run()
#3 /var/www/html/my-project/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Frame.php(126): Alchemy\BinaryDriver\AbstractBinary->command()
#4 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): FFMpeg\Media\Frame->save()
#5 /var/www/html/my-project/vendor/pbmedia/laravel-ffmpeg/src/Drivers/PHPFFMpeg.php(272): ProtoneMedia\LaravelFFMpeg\Drivers\PHPFFMpeg->forwardCallTo()
#6 /var/www/html/my-project/vendor/pbmedia/laravel-ffmpeg/src/Exporters/MediaExporter.php(223): ProtoneMedia\LaravelFFMpeg\Drivers\PHPFFMpeg->__call()
#7 /var/www/html/my-project/app/Jobs/ConvertVideoForStreaming.php(162): ProtoneMedia\LaravelFFMpeg\Exporters\MediaExporter->save()
#8 /var/www/html/my-project/app/Jobs/ConvertVideoForStreaming.php(131): App\Jobs\ConvertVideoForStreaming->exportFrame()
#9 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\ConvertVideoForStreaming->handle()
#10 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#12 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#13 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#14 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#15 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#16 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#18 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow()
#19 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#20 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#22 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#23 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#24 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#25 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#26 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker->runJob()
#27 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->daemon()
#28 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker()
#29 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#30 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#31 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#32 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#33 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#34 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#35 /var/www/html/my-project/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#36 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#37 /var/www/html/my-project/vendor/symfony/console/Application.php(1015): Illuminate\Console\Command->run()
#38 /var/www/html/my-project/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#39 /var/www/html/my-project/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#40 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#41 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#42 /var/www/html/my-project/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#43 {main}

Next ProtoneMedia\LaravelFFMpeg\Exporters\EncodingException: Unable to save frame in /var/www/html/my-project/vendor/pbmedia/laravel-ffmpeg/src/Exporters/EncodingException.php:12
Stack trace:
#0 /var/www/html/my-project/vendor/pbmedia/laravel-ffmpeg/src/Exporters/MediaExporter.php(237): ProtoneMedia\LaravelFFMpeg\Exporters\EncodingException::decorate()
#1 /var/www/html/my-project/app/Jobs/ConvertVideoForStreaming.php(162): ProtoneMedia\LaravelFFMpeg\Exporters\MediaExporter->save()
#2 /var/www/html/my-project/app/Jobs/ConvertVideoForStreaming.php(131): App\Jobs\ConvertVideoForStreaming->exportFrame()
#3 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\ConvertVideoForStreaming->handle()
#4 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#6 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#8 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#9 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#12 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#14 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#16 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#17 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#18 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#19 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#20 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker->runJob()
#21 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->daemon()
#22 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker()
#23 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#24 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#26 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#27 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#28 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#29 /var/www/html/my-project/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#30 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#31 /var/www/html/my-project/vendor/symfony/console/Application.php(1015): Illuminate\Console\Command->run()
#32 /var/www/html/my-project/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#33 /var/www/html/my-project/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#34 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#35 /var/www/html/my-project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#36 /var/www/html/my-project/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#37 {main}
```

**Comment by pascalbaljet** [comment]
What temporary directory are you using?

**Comment by c0mm4nDer** [comment]
I had same problem.
I Just add _%05d to filename :
```
FFMpeg::fromDisk('public')
            ->open($media->getDiskPath())
            ->getFrameFromSeconds(1)
            ->export()
            ->addFilter(function (FrameFilters $filters) {
                $filters->custom('scale=1280:720');
            })
            ->save($media->directory . '/' . $media->filename . '_%05d_thumb.jpg'); // <-- this line
```
Filename will be something like this: 
`yourfilename_000001_thumb.jpg`

also be sure your save directory has correct permission.
