### ISSUE TITLE
Error when scaling multiple resolutions

### ISSUE THREAD

**Issue by chikenare** [protonemedia/laravel-ffmpeg#527]
I get an error when I uncomment the other addFormat to scale

` 
 $format  = (new X264())->setPasses(1);

        $format->setAdditionalParameters([
            '-crf',
            '23',
        ]);

        try {
            FFMpeg::fromDisk('s3')
                ->open("Video/Download/{$this->transcode->video->uuid}.mkv")
                ->exportForHLS()
                ->toDisk('s3')
                ->onProgress(function ($percentage) {
                    $this->transcode->update(['progress' => $percentage]);
                })
                ->addFormat($format, function ($media) {
                    $media->scale(854, 480);
                })
                // ->addFormat($format, function ($media) {
                //     $media->scale(1280, 720);
                // })
                // ->addFormat($format, function ($media) {
                //     $media->scale(1920, 1080);
                // })
                ->save("Video/Stream/{$this->transcode->video->uuid}/index" . '.m3u8');
            $this->transcode->delete();
        } catch (Exception $e) {
            $this->transcode->update(['status' => TranscodeStatus::ERROR, 'message' => $e->getMessage()]);
            $this->delete();
        }
`

[2024-09-04 21:23:01] local.ERROR: ProtoneMedia\LaravelFFMpeg\Http\DynamicHLSPlaylist::parseLines(): Argument #1 ($lines) must be of type string, null given, called in /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php on line 30 {"exception":"[object] (TypeError(code: 0): ProtoneMedia\\LaravelFFMpeg\\Http\\DynamicHLSPlaylist::parseLines(): Argument #1 ($lines) must be of type string, null given, called in /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php on line 30 at /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Http/DynamicHLSPlaylist.php:157)
[stacktrace]
#0 /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php(30): ProtoneMedia\\LaravelFFMpeg\\Http\\DynamicHLSPlaylist::parseLines()
#1 /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php(47): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator->getStreamInfoLine()
#2 [internal function]: ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator->ProtoneMedia\\LaravelFFMpeg\\Exporters\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\\Support\\Arr::map()
#5 /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSPlaylistGenerator.php(46): Illuminate\\Support\\Collection->map()
#6 /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSExporter.php(316): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSPlaylistGenerator->get()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(747): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSExporter->ProtoneMedia\\LaravelFFMpeg\\Exporters\\{closure}()
#8 /var/www/html/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSExporter.php(313): Illuminate\\Support\\Collection->pipe()
#9 /var/www/html/app/Jobs/Videos/ConvertVideoForStreaming.php(53): ProtoneMedia\\LaravelFFMpeg\\Exporters\\HLSExporter->save()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Videos\\ConvertVideoForStreaming->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Pipeline\\Pipeline->then()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(139): Illuminate\\Queue\\Worker->daemon()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(122): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call()
#36 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#38 /var/www/html/vendor/symfony/console/Application.php(1049): Illuminate\\Console\\Command->run()
#39 /var/www/html/vendor/symfony/console/Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand()
#40 /var/www/html/vendor/symfony/console/Application.php(169): Symfony\\Component\\Console\\Application->doRun()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1187): Illuminate\\Foundation\\Console\\Kernel->handle()
#43 /var/www/html/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#44 {main}
"}

**Comment by chikenare** [comment]
Apparently an instance is necessary for each format.
 $format1 = new X264();
 $format2 = new X264();
 $format3 = new X264();

Is this normal? Can't it be reused?
